# Site Info
title: Udayshankar Ravikumar
author: Udayshankar Ravikumar
email: uralstech@gmail.com
description: > 
  Udayshankar Ravikumar, PCAP and Chief Technology Officer at URAV ADVANCED LEARNING SYSTEMS PRIVATE LIMITED.

timezone: Asia/Kolkata
show_excerpts: true

url: "https://uralstech.github.io"

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# Jekyll Dash Settings
dash:
  date_format: "%d/%m/%Y"
  show_author: true
  animation_speed: 50
  rtl: false

  # Social Links (converted from Beautiful Jekyll format)
  social_links:
    - url: https://twitter.com/uralstechCTO
      icon: twitter-square
      color: blue
    - url: https://www.linkedin.com/in/udayshankar-ctourals
      icon: linkedin
      color: indigo
    - url: https://github.com/Uralstech
      icon: github-square
      color: purple
    - url: https://www.facebook.com/100082467614963
      icon: facebook-square
      color: blue
    - url: https://www.reddit.com/user/uralstech_MR
      icon: reddit
      color: orange
    - url: https://www.youtube.com/@uralstechnologies9017
      icon: youtube-square
      color: red
    - url: https://gitlab.com/Uralstech
      icon: gitlab
      color: orange
    - url: https://www.hackerrank.com/Uralstech
      icon: hackerrank
      color: green
    - url: mailto:uralstech@gmail.com
      icon: envelope
      color: gray

# Build Settings
theme: jekyll-dash

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - liquid-md5
  - jekyll/tagging
  - jekyll-sitemap

# Optional GitHub username (for GitHub avatar integration)
github_username: Uralstech
avatar_source: github

# Optional: Exclude from build
exclude:
  - README.md
