# Site Info
title: Udayshankar Ravikumar
author: Udayshankar Ravikumar
email: udayshankar.cto@uralstech.in
description: > 
  Hi! I'm Udayshankar Ravikumar, PCAP and Chief Technology Officer at Urav Advanced Learning Systems Pvt Ltd. This blog is for documentating my open source work.

timezone: Asia/Kolkata
show_excerpts: true

url: "https://uralstech.github.io"

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# Jekyll Dash Settings
dash:
  date_format: "%d/%m/%Y"
  show_author: true
  animation_speed: 50
  rtl: false

  # Social Links
  social_links:
    - url: https://twitter.com/uralstechCTO
      icon: square-x-twitter
      color: pink
    - url: https://www.youtube.com/@uralstechnologies9017
      icon: youtube-square
      color: red
    - url: https://github.com/Uralstech
      icon: github-square
      color: purple
    - url: https://www.linkedin.com/in/udayshankar-ctourals
      icon: linkedin
      color: blue
    - url: https://www.reddit.com/user/uralstech_MR
      icon: square-reddit
      color: orange
    - url: mailto:udayshankar.cto@uralstech.in
      icon: inbox
      color: indigo

# Build Settings
theme: jekyll-dash

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-sitemap

# Optional GitHub username (for GitHub avatar integration)
github_username: Uralstech
avatar_source: github

# Optional: Exclude from build
exclude:
  - README.md
